-- Migration 09: depth-maps Supabase Storage bucket
-- Stores procedural depth map PNGs generated by the v2 BTI pipeline.
-- Public bucket — Flux Depth Pro needs a plain HTTPS URL for control_image.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'depth-maps',
  'depth-maps',
  true,
  5242880,                -- 5 MB per file
  ARRAY['image/png']
)
ON CONFLICT (id) DO NOTHING;

-- Service role (supabaseServer) bypasses RLS, but we add policies so
-- the authenticated role can also read its own depth maps if needed.

CREATE POLICY "depth-maps: service role full access"
  ON storage.objects FOR ALL
  TO service_role
  USING (bucket_id = 'depth-maps')
  WITH CHECK (bucket_id = 'depth-maps');

CREATE POLICY "depth-maps: public read"
  ON storage.objects FOR SELECT
  TO public
  USING (bucket_id = 'depth-maps');
